app/urls.py
from django.urls import path
from .views import home,registro,contacto,agregar_producto,listar_productos,\
    modificar_producto,eliminar_producto

urlpatterns = [
    path('',home,name='home'),
    path('registro/',registro,name='registro'),
    path('contacto/',contacto,name='contacto'),
    path('listar-productos/', listar_productos,name='listar_productos'),
    path('agregar-producto/', agregar_producto,name='agregar_producto'),
    path('modificar-producto/<id>/', modificar_producto,name='modificar_producto'),
    path('eliminar-producto/<id>/', eliminar_producto,name='eliminar_producto'),
]

onlyflans/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pwa.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.
opciones_consultas = [
    [0,'consulta'],
    [1,'reclamo'],
    [2,'sugerencia'],
    [3,'felicitaciones']
]
class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField()

    def __str__(self):
        return self.nombre

class Flan(models.Model):
    nombre = models.CharField(max_length=30)
    precio = models.IntegerField(default=0)
    imagen = models.ImageField(upload_to='productos')

    def __str__(self):
        return self.nombre

app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ValidationError
from .models import Contacto,Flan


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class ContactoForm(forms.ModelForm):

    class Meta:
        model = Contacto
        fields = '__all__'

class FlanForm(forms.ModelForm):
    nombre = forms.CharField(min_length=3,max_length=30)
    precio = forms.IntegerField(min_value=1,max_value=200000)
    
    class Meta:
        model = Flan
        fields = '__all__'

app/views.py
import re
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate,login
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib import messages
from django.forms import ValidationError
from django.contrib.auth.decorators import permission_required
from .forms import CustomUserCreationForm,ContactoForm, FlanForm
from .models import Flan

# Create your views here.

def home(request):
    flanes = Flan.objects.all()
    data = {
        'flanes': flanes
    }
    return render(request,'app/index.html',data)

def registro(request):
    data = {
        'form':CustomUserCreationForm()
    }
    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data['username'],password=formulario.cleaned_data['password1'])
            login(request,user)
            return redirect(to='home')
        data['form'] = formulario
    return render(request,'registration/registro.html',data)

def contacto(request):
    data = {
        'form': ContactoForm()
    }
    if request.method == 'POST':
        formulario = ContactoForm(data = request.POST)
        if formulario.is_valid():
            formulario.save()
            data['mensaje'] = "Solicitud de Contacto Generada."
        else:
            data['form'] = formulario
    return render(request,'app/contacto.html',data)

def agregar_producto(request):
    data = {
        'form':FlanForm()
    }
    if request.method == 'POST':
        formulario = FlanForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request,"Flan Registrado")
            return redirect(to='listar_productos')
        else:
            data['form'] = formulario

    return render(request,'app/producto/agregar.html',data)

def listar_productos(request):
    flanes = Flan.objects.all()
    page = request.GET.get('page',1)
    try:
        paginator = Paginator(flanes,4)
        flanes = paginator.page(page)
    except:
        raise Http404
    
    data = {
        'entity':flanes,
        'paginator':paginator
    }
    return render(request,'app/producto/listar.html',data)

def modificar_producto(request,id):
    producto = get_object_or_404(Flan,id=id)
    data = {
        'form':FlanForm(instance=producto)
    }
    if request.method == 'POST':
        formulario = FlanForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request,"flan modificado correctamente")
            return redirect(to="listar_productos")
        data['form'] = formulario

    return render(request, 'app/producto/modificar.html',data)

@permission_required('app.delete_flan')
def eliminar_producto(request,id):
    flan = get_object_or_404(Flan,id = id)
    flan.delete()
    messages.success(request,"Flan eliminado correctamente")

    return redirect(to="listar_productos")

app/templates/app/base/base.html
<!doctype html>
<html lang="en">
    {% load static %}
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        
    <!-- Favicon -->
    <link rel="shortcut icon" type="icon" href="{% static 'app/img/favicon.png' %}"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;500&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
        integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">

    <title>“Bienvenido a onlyflans"</title>

    <!-- pwa aqui -->
    {% load pwa %}

    {% progressive_web_app_meta %}

</head>
<body>
    <!-- header & navbar -->
    {% block 'header' %}
    {% include 'app/base/header.html' %}
    {% endblock %}

    <!-- contenido -->
    {% block 'content' %}
    {% endblock %}

    <!-- footer -->
    {% block 'footer' %}
    {% include 'app/base/footer.html' %}
    {% endblock %}

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    <!-- sweetalert2 -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- JavaScript -->
    <script src="{% static 'app/js/app.js' %}"></script>
    {% block mensajeria %}
    {% if messages %}
        {% for m in messages %}
        <script>
            Swal.fire({
                "title":"Felicitaciones",
                "text":"{{m}}",
                "icon":"success"
            })
        </script>
        {% endfor %}
    {% endif %}
    {% endblock %}
    
    {% block js %}
    {% endblock %}
</body>
</html>

app/templates/app/base/carousel.html
{% block carousel %}
<div class="container">

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'app/img/carousel/flan1.png' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'app/img/carousel/flan6.png' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'app/img/carousel/flan5.png' %}" class="d-block w-100" alt="...">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-target="#carouselExampleIndicators" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-target="#carouselExampleIndicators" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </button>
      </div>

</div>
{% endblock %}

app/templates/app/base/footer.html
{% block 'footer' %}
{% load static %}
<footer class="container-fluid bg-light text-black">
    <div class="row">
        <div class="col-md-6 offset-md-3 text-center text-white">
          <h5 class="text-black">onlyflans</h5>
          <a href="https://www.github.com" target="_blank"><i class="fab fa-github-square mx-1 fa-3x"></i></a>
          <a href="https://www.linkedin.com" target="_blank"><i class="fab fa-linkedin mx-1 fa-3x"></i></a>
          <a href="https://www.twitter.com" target="_blank"> <i class="fab fa-twitter-square mx-1 fa-3x"></i></a>
          <a href="https://www.facebook.com" target="_blank"> <i class="fab fa-facebook-square mx-1 fa-3x"></i></a>
      </div>
    </div>
  </footer>
{% endblock %}

app/templates/app/base/header.html
{% block 'header' %}
{% load static %}
<header class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand ml-5" href="{% url 'home' %}">
            <img src="{% static 'app/img/logo_black.png' %}" width="80" alt="logo_onlyflans">
        </a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <h2 class="ml-auto text-black pl-5">Blog de Flanes</h2>
                <ul class="navbar-nav ml-auto ">
                <li class="nav-item">
                    <a class="nav-link" href="{%  url 'home' %}">home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%  url 'contacto' %}">contacto</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'agregar_producto' %}">agregar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'listar_productos' %}">listar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%  url 'logout' %}">cerrar sesión</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">@{{ user.username }}</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{%  url 'login' %}">publicar</a>
                </li>
                <li class="nav-item">
                    <!-- <a class="nav-link" href="{%  url 'registro' %}">registrate</a> -->
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

</header>
{% endblock %}

app/templates/app/contacto.html
{% extends 'app/base/base.html' %}

{% block 'content' %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h2 class="text-left">Contactanos</h2><hr>
                    <form action="" method="post">
                        {% csrf_token %}
                        {{form | crispy }}
                        <!-- <a href="{% url 'home' %}">ir a home</a> -->
                        <input type="submit" value="enviar" class="btn btn-success float-right">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/index copy.html
{% extends 'app/base/base.html' %}

  {% block 'content' %}
  {% load static %}
  <div class="container-fluid">

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'app/img/carousel/flan1.png' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="{% static 'app/img/carousel/flan6.png' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="{% static 'app/img/carousel/flan5.png' %}" class="d-block w-100" alt="...">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-target="#carouselExampleIndicators" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-target="#carouselExampleIndicators" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </button>
    </div>


  <!-- Hero Section -->
  <section class="container-fluid" id="servicios">
    <h2 class="text-center display-5 text-secondary pt-4 my-4 fw-bold d-none d-sm-block">Nuestros Productos</h2>
    <div class="row row-cols-sm-1 row-cols-md-2 row-cols-lg-3">

    <!-- Cards -->
      <div class="col py-4">
        <div class="card mx-auto" style="width: 18rem;">
          <img src="{% static 'app/img/muestra/flan1.jpg' %}" class="card-img-top" alt="imagen-plumon">
          <div class="card-body">
            <h6 class="card-subtitle mb-2  text-lighter fw-light display-6">Lorem ipsum dolor sit amet consectetur adipisicing elit.    </h6>
            <p class="card-text text-muted mb-0 pb-0 fw-light">Plumones Manolino
              <br>
              <small class="text-muted">
                <span>
                  <i class="fas fa-map-marker-alt text-muted px-2"></i>
                </span>9191 Avenida Vitacura, Chile
              </small>
            </p>
            <hr class="w-80 mx-auto my-2 py-0" style="color: grey;" />
            <p class="card-text text-end text-muted py-3">$45.990<span class="text-success fw-normal fs-4 mx-2">$22.990</span></p>
          </div>
        </div>
      </div>
    <!-- fin Cards  -->

        <!-- Cards -->
        <div class="col py-4">
            <div class="card mx-auto" style="width: 18rem;">
              <img src="{% static 'app/img/muestra/flan1.jpg' %}" class="card-img-top" alt="imagen-plumon">
              <div class="card-body">
                <h6 class="card-subtitle mb-2  text-lighter fw-light display-6">Plumón Coral Fleece estampado en modelo y tamaño a elección</h6>
                <p class="card-text text-muted mb-0 pb-0 fw-light">Plumones Manolino
                  <br>
                  <small class="text-muted">
                    <span>
                      <i class="fas fa-map-marker-alt text-muted px-2"></i>
                    </span>9191 Avenida Vitacura, Chile
                  </small>
                </p>
                <hr class="w-80 mx-auto my-2 py-0" style="color: grey;" />
                <p class="card-text text-end text-muted py-3">$45.990<span class="text-success fw-normal fs-4 mx-2">$22.990</span></p>
              </div>
            </div>
          </div>
        <!-- fin Cards  -->

            <!-- Cards -->
      <div class="col py-4">
        <div class="card mx-auto" style="width: 18rem;">
          <img src="{% static 'app/img/muestra/flan1.jpg' %}" class="card-img-top" alt="imagen-plumon">
          <div class="card-body">
            <h6 class="card-subtitle mb-2  text-lighter fw-light display-6">Plumón Coral Fleece estampado en modelo y tamaño a elección</h6>
            <p class="card-text text-muted mb-0 pb-0 fw-light">Plumones Manolino
              <br>
              <small class="text-muted">
                <span>
                  <i class="fas fa-map-marker-alt text-muted px-2"></i>
                </span>9191 Avenida Vitacura, Chile
              </small>
            </p>
            <hr class="w-80 mx-auto my-2 py-0" style="color: grey;" />
            <p class="card-text text-end text-muted py-3">$45.990<span class="text-success fw-normal fs-4 mx-2">$22.990</span></p>
          </div>
        </div>
      </div>
    <!-- fin Cards  -->
    
                <!-- Cards -->
                <div class="col py-4">
                  <div class="card mx-auto" style="width: 18rem;">
                    <img src="{% static 'app/img/muestra/flan1.jpg' %}" class="card-img-top" alt="imagen-plumon">
                    <div class="card-body">
                      <h6 class="card-subtitle mb-2  text-lighter fw-light display-6">Plumón Coral Fleece estampado en modelo y tamaño a elección</h6>
                      <p class="card-text text-muted mb-0 pb-0 fw-light">Plumones Manolino
                        <br>
                        <small class="text-muted">
                          <span>
                            <i class="fas fa-map-marker-alt text-muted px-2"></i>
                          </span>9191 Avenida Vitacura, Chile
                        </small>
                      </p>
                      <hr class="w-80 mx-auto my-2 py-0" style="color: grey;" />
                      <p class="card-text text-end text-muted py-3">$45.990<span class="text-success fw-normal fs-4 mx-2">$22.990</span></p>
                    </div>
                  </div>
                </div>
              <!-- fin Cards  -->

                          <!-- Cards -->
      <div class="col py-4">
        <div class="card mx-auto" style="width: 18rem;">
          <img src="{% static 'app/img/muestra/flan1.jpg' %}" class="card-img-top" alt="imagen-plumon">
          <div class="card-body">
            <h6 class="card-subtitle mb-2  text-lighter fw-light display-6">Plumón Coral Fleece estampado en modelo y tamaño a elección</h6>
            <p class="card-text text-muted mb-0 pb-0 fw-light">Plumones Manolino
              <br>
              <small class="text-muted">
                <span>
                  <i class="fas fa-map-marker-alt text-muted px-2"></i>
                </span>9191 Avenida Vitacura, Chile
              </small>
            </p>
            <hr class="w-80 mx-auto my-2 py-0" style="color: grey;" />
            <p class="card-text text-end text-muted py-3">$45.990<span class="text-success fw-normal fs-4 mx-2">$22.990</span></p>
          </div>
        </div>
      </div>
    <!-- fin Cards  -->

    <!-- Cards -->
    <div class="col py-4">
      <div class="card mx-auto" style="width: 18rem;">
        <img src="{% static 'app/img/muestra/flan2.jpg' %}" class="card-img-top" alt="imagen-plumon">
        <div class="card-body">
          <!-- <hr class=" py-1 " style="border-color: grey;border-width: 2px;" /> -->
          <p class="card-text text-info text-center mb-0 pb-0 fw-light">Flan de Chocolate</p>
        </div>
      </div>
    </div>
  <!-- fin Cards  -->



    </div>
  </section>
    
  </div>
  {% endblock %}

app/templates/app/index.html
{% extends 'app/base/base.html' %}

{% block 'content' %}
{% load static %}

<div class="container-fluid">

  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'app/img/carousel/flan1.png' %}" class="d-block w-100" alt="flanes">
      </div>
      <div class="carousel-item">
        <img src="{% static 'app/img/carousel/flan6.png' %}" class="d-block w-100" alt="flanes">
      </div>
      <div class="carousel-item">
        <img src="{% static 'app/img/carousel/flan5.png' %}" class="d-block w-100" alt="flanes">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-target="#carouselExampleIndicators" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-target="#carouselExampleIndicators" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </button>
  </div>
  {% load humanize %}
  <!-- Hero Section -->
  <section class="container-fluid" id="servicios">
    <h2 class="text-center display-5 text-secondary pt-4 my-4 fw-bold d-none d-sm-block">Nuestros Flanes</h2>
    <div class="row row-cols-sm-1 row-cols-md-2 row-cols-lg-3">
      <!-- Cards -->
      {% for p in flanes %}
      <div class="col py-4">
        <div class="card mx-auto" style="width: 18rem;">
          {% if p.imagen %}
          <img src="{{ p.imagen.url }}" class="card-img-top" alt="imagen-plumon">
          {% endif %}
          <div class="card-body">
            <p class="card-text text-info mb-0 pb-0 fw-light">{{ p.nombre | title }}</p>
            <hr class=" py-1 " style="border-color: grey;border-width: 2px;" />
            <span>${{ p.precio | intcomma }}</span>
          </div>
        </div>
      </div>
      <!-- EndCards  -->
      {% endfor %}

    </div>
  </section>
  
</div>
{% endblock %}

app/templates/app/paginator.html
{% if paginator.num_pages > 1 %}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

app/templates/app/producto/agregar.html
{% extends 'app/base/base.html' %}

{% block 'content' %}

{% load crispy_forms_tags %}
<br>
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <h2>Nuevo Flan</h2><hr>
                <form action="" method="post" enctype="multipart/form-data">

                    {% csrf_token %}
                    {{ form | crispy }}
<br>
                    <div class="d-flex justify_content_end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <input type="submit" value="Guardar" class="btn btn-primary">
                    </div>

                </form>
                {{ mensaje }}
            </div>
        </div>

    </div>
</div>

{% endblock %}

app/templates/app/producto/listar.html
{% extends 'app/base/base.html' %}

{% block js %}
<script>
    function eliminarProducto(id){
        console.log(id)
        Swal.fire({
            "title":"¿Estas Seguro?",
            "text":"está acción no se puede deshacer!!!!",
            "icon":"question",
            "showCancelButton":true,
            "cancelButtonText":"No, Cancelar",
            "confirmButtonText":"Sí, Eliminar",
            "reverseButtons":true,
            "confirmButtonColor":"#dc3545",
        })
        .then(function(result){
            if(result.isConfirmed){
                window.location.href = "/eliminar-producto/"+id+"/"
            }
        })
    }
</script>
{% endblock %}

{% block 'content' %}
{% load humanize %}
<br><br><br>
<div class="container">
<div class="card">
    <div class="card-body">
        <h2>Listado de Flanes</h2><hr>
        <table class="table table-striped table-hover table-responsive-sm">
            <tr>
                <th>Nombre</th>
                <th>Precio</th>
                {% if perms.app.change_flan %}
                <th>Opciones</th>
                {% endif %}
            </tr>
        
            {% for p in entity %}
            <tr>
                <td>{{ p.nombre | title }}</td>
                <td>${{ p.precio | intcomma }}</td>
                {% if perms.app.change_flan %}
                <td>
                    <a href="{% url 'modificar_producto' p.id %}" class="btn btn-info btn-sm">modificar</a>
                    <a href="#" onclick="eliminarProducto({{p.id}})" class="btn btn-danger btn-sm">eliminar</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table><hr>
        <div>
            {% include 'app/paginator.html' %}
        </div>
    </div>
</div>

</div>

{% endblock %}

app/templates/app/producto/modificar.html
{% extends 'app/base/base.html' %}

{% block 'content' %}

{% load crispy_forms_tags %}
<br>
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <h2>Editar producto</h2><hr>
                <form action="" method="post" enctype="multipart/form-data">

                    {% csrf_token %}
                    {{ form | crispy }}
<br>
                    <div class="d-flex justify_content_end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <input type="submit" value="Editar" class="btn btn-primary">
                    </div>

                </form>
                {{ mensaje }}
            </div>
        </div>

    </div>
</div>

{% endblock %}